"use client";

import {
  Group,
  Person,
  CalendarMonth,
  AttachMoney,
  ShoppingCart,
  LocalShipping,
  ReportProblem,
  Check,
  Dashboard,
  TrendingUp,
  TrendingDown,
  CreditCard,
  Add,
  Remove,
  Close,
  Search,
  Assignment,
  ChevronRight,
  ChevronLeft,
  Inventory2,
  Phone,
  Email,
  LocationOn,
  Logout,
  Print,
  Delete,
  Edit,
  Description,
  Block,
  Autorenew,
  Undo,
  AssignmentReturn,
  Security,
  Lock,
  TrackChanges,
  Timeline,
  FilterList,
  Tune,
  MoreHoriz,
  ErrorOutline,
  AutoAwesome,
  AccountBalanceWallet,
  Insights,
  Payments,
  Bolt,
  KeyboardArrowUp,
  KeyboardArrowDown,
  Language,
  // Inventory Specific
  Chair,
  TableBar,
  Restaurant,
  WineBar,
  LocalFlorist,
  Festival,
  Speaker,
  Lightbulb,
  Power,
  Weekend,
  Kitchen,
  CameraAlt,
  Videocam,
  Piano,
  Celebration,
  WbSunny,
  DarkMode,
  SettingsBrightness,
  Visibility,
  VisibilityOff,
  Laptop,
  Launch,
  Menu,
  VpnKey,
  Info,
  HelpOutline,
  Settings,
  ShoppingBag,
  LocalOffer,
  FileDownload
} from '@mui/icons-material';

// --- SYSTEM ICONS (Replacements for Lucide) ---
export const Icons = {
  Users: Group,
  User: Person,
  Calendar: CalendarMonth,
  DollarSign: AttachMoney,
  ShoppingCart: ShoppingCart,
  Truck: LocalShipping,
  AlertOctagon: ReportProblem,
  Check: Check,
  LayoutDashboard: Dashboard,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  CreditCard: CreditCard,
  Plus: Add,
  Minus: Remove,
  X: Close,
  Search: Search,
  ClipboardList: Assignment,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Package: Inventory2,
  Phone: Phone,
  Mail: Email,
  MapPin: LocationOn,
  LogOut: Logout,
  Printer: Print,
  Trash2: Delete,
  Pencil: Edit,
  FileText: Description,
  Ban: Block,
  Loader2: Autorenew,
  Undo: Undo,
  ReturnIcon: AssignmentReturn,
  Shield: Security,
  Lock: Lock,
  Target: TrackChanges,
  Activity: Timeline,
  Filter: FilterList,
  SlidersHorizontal: Tune,
  MoreHorizontal: MoreHoriz,
  AlertCircle: ErrorOutline,
  Sparkles: AutoAwesome,
  Wallet: AccountBalanceWallet,
  BarChart: Insights,
  Cash: Payments,
  Zap: Bolt,
  SortUp: KeyboardArrowUp,
  SortDown: KeyboardArrowDown,
  ChevronDown: KeyboardArrowDown,
  ChevronUp: KeyboardArrowUp,
  Sun: WbSunny,
  Moon: DarkMode,
  Monitor: SettingsBrightness,
  Laptop: Laptop,
  Eye: Visibility,
  EyeOff: VisibilityOff,
  Globe: Language,
  ExternalLink: Launch,
  Menu: Menu,
  Key: VpnKey,
  Info: Info,
  HelpCircle: HelpOutline,
  Settings: Settings,
  ShoppingBag: ShoppingBag,
  Tag: LocalOffer,
  Download: FileDownload
};

import React from 'react';

// --- INVENTORY PICKER ICONS ---
// These keys will be stored in the database as "icon:Chair", "icon:Table", etc.
export const InventoryIcons: Record<string, React.ComponentType<{ className?: string }>> = {
  Chair: Chair,
  Table: TableBar,
  Cutlery: Restaurant,
  Glassware: WineBar,
  Decor: LocalFlorist,
  Tent: Festival,
  Speaker: Speaker,
  Lighting: Lightbulb,
  Power: Power,
  Sofa: Weekend,
  Catering: Kitchen,
  Photo: CameraAlt,
  Video: Videocam,
  Music: Piano,
  Party: Celebration
};