"use client";

import {
  Group,
  Person,
  CalendarMonth,
  AttachMoney,
  ShoppingCart,
  LocalShipping,
  ReportProblem,
  Check,
  Dashboard,
  TrendingUp,
  CreditCard,
  Add,
  Remove,
  Close,
  Search,
  Assignment,
  ChevronRight,
  ChevronLeft,
  Inventory2,
  Phone,
  Email,
  LocationOn,
  Logout,
  Print,
  Delete,
  Edit,
  Description,
  Block,
  // Inventory Specific
  Chair,
  TableBar,
  Restaurant,
  WineBar,
  LocalFlorist,
  Festival,
  Speaker,
  Lightbulb,
  Power,
  Weekend,
  Kitchen,
  CameraAlt,
  Videocam,
  Piano,
  Celebration
} from '@mui/icons-material';

// --- SYSTEM ICONS (Replacements for Lucide) ---
export const Icons = {
  Users: Group,
  User: Person,
  Calendar: CalendarMonth,
  DollarSign: AttachMoney,
  ShoppingCart: ShoppingCart,
  Truck: LocalShipping,
  AlertOctagon: ReportProblem,
  Check: Check,
  LayoutDashboard: Dashboard,
  TrendingUp: TrendingUp,
  CreditCard: CreditCard,
  Plus: Add,
  Minus: Remove,
  X: Close,
  Search: Search,
  ClipboardList: Assignment,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Package: Inventory2,
  Phone: Phone,
  Mail: Email,
  MapPin: LocationOn,
  LogOut: Logout,
  Printer: Print,
  Trash2: Delete,
  Pencil: Edit,
  FileText: Description,
  Ban: Block
};

// --- INVENTORY PICKER ICONS ---
// These keys will be stored in the database as "icon:Chair", "icon:Table", etc.
export const InventoryIcons: Record<string, any> = {
  Chair: Chair,
  Table: TableBar,
  Cutlery: Restaurant,
  Glassware: WineBar,
  Decor: LocalFlorist,
  Tent: Festival,
  Speaker: Speaker,
  Lighting: Lightbulb,
  Power: Power,
  Sofa: Weekend,
  Catering: Kitchen,
  Photo: CameraAlt,
  Video: Videocam,
  Music: Piano,
  Party: Celebration
};
