-- Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

-- Custom Enums
CREATE TYPE public.discount_value_type AS ENUM ('fixed', 'percentage');
CREATE TYPE public.discount_duration_type AS ENUM ('one_time', 'period', 'unlimited');
CREATE TYPE public.promotion_status AS ENUM ('active', 'expired', 'upcoming');
CREATE TYPE public.approval_strategy_type AS ENUM ('auto', 'manual');


CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'client'::text])),
    username text,
    email text,
    first_name text,
    last_name text,
    phone text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.clients (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    first_name text,
    last_name text,
    username text UNIQUE,
    email text,
    phone text,
    address text,
    image text DEFAULT 'icon:User',
    color text DEFAULT 'text-primary',
    total_orders integer DEFAULT 0,
    total_spent numeric DEFAULT 0.00,
    last_order timestamptz,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.inventory (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    category text NOT NULL,
    stock integer NOT NULL DEFAULT 0 CHECK (stock >= 0),
    price numeric NOT NULL DEFAULT 0.00,
    replacement_cost numeric NOT NULL DEFAULT 0.00,
    maintenance integer DEFAULT 0,
    image text,
    color text,
    sort_order numeric,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.discounts (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    code text NOT NULL UNIQUE,
    discount_type public.discount_value_type NOT NULL,
    discount_value numeric NOT NULL,
    duration_type public.discount_duration_type NOT NULL,
    start_date date,
    end_date date,
    status public.promotion_status NOT NULL,
    approval_strategy public.approval_strategy_type NOT NULL,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.discounts ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.orders (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer REFERENCES public.clients(id) ON DELETE SET NULL,
    client_name text,
    email text,
    phone text,
    status text NOT NULL DEFAULT 'Pending'::text,
    start_date date NOT NULL,
    end_date date NOT NULL,
    total_amount numeric NOT NULL DEFAULT 0.00,
    amount_paid numeric DEFAULT 0.00,
    penalty_amount numeric DEFAULT 0.00,
    deposit_paid boolean DEFAULT false,
    return_status text,
    item_integrity text,
    closed_at timestamptz,
    discount_name text,
    discount_type public.discount_value_type,
    discount_value numeric DEFAULT 0,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.order_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer REFERENCES public.orders(id) ON DELETE CASCADE,
    inventory_id integer REFERENCES public.inventory(id) ON DELETE SET NULL,
    quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price numeric,
    returned_qty integer DEFAULT 0,
    lost_qty integer DEFAULT 0,
    damaged_qty integer DEFAULT 0,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.discount_redemptions (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    discount_id bigint REFERENCES public.discounts(id) ON DELETE CASCADE,
    order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE,
    client_id bigint REFERENCES public.clients(id) ON DELETE CASCADE,
    applied_at timestamptz DEFAULT now(),
    discount_amount_applied numeric NOT NULL,
    approval_status text NOT NULL DEFAULT 'pending' CHECK (approval_status = ANY (ARRAY['approved'::text, 'pending'::text, 'rejected'::text]))
);
ALTER TABLE public.discount_redemptions ENABLE ROW LEVEL SECURITY;


CREATE TABLE public.settings (
    key text PRIMARY KEY,
    value text NOT NULL
);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;


CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
BEGIN
  RETURN (
    SELECT (auth.jwt() ->> 'role' = 'service_role')
    OR 
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );
END;
$function$;


CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  is_admin boolean;
  existing_client_id int;
  provided_token text;
  required_token text;
begin
  -- 1. Extract and Validate Token/Role
  is_admin := (new.raw_user_meta_data->>'role' = 'admin');
  provided_token := new.raw_user_meta_data->>'signup_token';

  select value into required_token from public.settings where key = 'signup_token';

  if is_admin then
    if required_token is not null and (provided_token is null or provided_token != required_token) then
      raise exception 'Unauthorized: Valid security token required for admin signup.';
    end if;
  end if;

  if new.raw_user_meta_data->>'role' not in ('admin', 'client') then
      raise exception 'Unauthorized: Invalid role specified.';
  end if;

  -- 2. Create Profile
  insert into public.profiles (id, role, username, email, first_name, last_name, phone, updated_at)
  values (
    new.id, 
    case when is_admin then 'admin' else 'client' end,
    coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)),
    new.email,
    coalesce(new.raw_user_meta_data->>'first_name', ''),
    coalesce(new.raw_user_meta_data->>'last_name', ''),
    coalesce(new.raw_user_meta_data->>'phone', ''),
    now()
  );

  -- 3. Create/Link Client if not admin
  if not is_admin then
    select id into existing_client_id 
    from public.clients 
    where lower(email) = lower(new.email) and user_id is null 
    limit 1;

    if existing_client_id is not null then
      update public.clients set
        user_id = new.id,
        first_name = coalesce(new.raw_user_meta_data->>'first_name', first_name),
        last_name = coalesce(new.raw_user_meta_data->>'last_name', last_name),
        username = coalesce(new.raw_user_meta_data->>'username', username),
        phone = coalesce(new.raw_user_meta_data->>'phone', phone)
      where id = existing_client_id;
    else
      insert into public.clients (user_id, first_name, last_name, username, email, phone, total_orders, total_spent, image, color)
      values (new.id, coalesce(new.raw_user_meta_data->>'first_name', ''), coalesce(new.raw_user_meta_data->>'last_name', ''), coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)), new.email, coalesce(new.raw_user_meta_data->>'phone', ''), 0, 0, 'icon:User', 'text-primary');
    end if;
  end if;
  return new;
end;
$function$;

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();


CREATE OR REPLACE FUNCTION public.submit_order(p_client_id bigint, p_client_name text, p_phone text, p_email text, p_start_date date, p_end_date date, p_total_amount numeric, p_items jsonb, p_order_id bigint DEFAULT NULL::bigint)
 RETURNS bigint
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
  new_order_id bigint;
  item jsonb;
  v_available integer;
  v_item_id bigint;
  v_qty integer;
BEGIN
  IF p_order_id IS NOT NULL THEN
    UPDATE orders SET client_id = p_client_id, client_name = p_client_name, phone = p_phone, email = p_email, start_date = p_start_date, end_date = p_end_date, total_amount = p_total_amount, status = 'Pending' WHERE id = p_order_id RETURNING id INTO new_order_id;
    DELETE FROM order_items WHERE order_id = new_order_id;
  ELSE
    INSERT INTO orders (client_id, client_name, phone, email, start_date, end_date, total_amount, status) VALUES (p_client_id, p_client_name, p_phone, p_email, p_start_date, p_end_date, p_total_amount, 'Pending') RETURNING id INTO new_order_id;
  END IF;

  FOR item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_item_id := (item->>'inventory_id')::bigint;
    v_qty := (item->>'quantity')::integer;
    PERFORM 1 FROM inventory WHERE id = v_item_id FOR UPDATE;

    SELECT (i.stock - COALESCE(SUM(oi.quantity), 0))::integer INTO v_available
    FROM inventory i
    LEFT JOIN order_items oi ON i.id = oi.inventory_id
    LEFT JOIN orders o ON oi.order_id = o.id
    WHERE i.id = v_item_id AND o.status IN ('Pending', 'Approved', 'Active', 'Late', 'Overdue') AND o.start_date <= p_end_date AND o.end_date >= p_start_date AND o.id != new_order_id GROUP BY i.id;
    
    IF v_available IS NULL THEN SELECT stock INTO v_available FROM inventory WHERE id = v_item_id; END IF;
    IF v_available < v_qty THEN RAISE EXCEPTION 'Insufficient stock for item ID %. Requested: %, Available: %', v_item_id, v_qty, v_available; END IF;
    INSERT INTO order_items (order_id, inventory_id, quantity, unit_price) VALUES (new_order_id, v_item_id, v_qty, (item->>'unit_price')::numeric);
  END LOOP;
  RETURN new_order_id;
END;
$function$;


CREATE OR REPLACE FUNCTION public.calculate_expected_order_total(p_order_id integer)
 RETURNS numeric
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
DECLARE
    v_subtotal numeric := 0;
    v_duration integer;
    v_start_date date;
    v_end_date date;
    v_discount_type text;
    v_discount_value numeric;
    v_penalty numeric;
    v_total numeric;
BEGIN
    SELECT start_date, end_date, discount_type, discount_value, penalty_amount INTO v_start_date, v_end_date, v_discount_type, v_discount_value, v_penalty FROM orders WHERE id = p_order_id;
    v_duration := (v_end_date - v_start_date) + 1;
    IF v_duration < 1 THEN v_duration := 1; END IF;
    SELECT COALESCE(SUM(quantity * unit_price), 0) * v_duration INTO v_subtotal FROM order_items WHERE order_id = p_order_id;
    v_total := v_subtotal;
    IF v_discount_type = 'fixed' THEN v_total := v_total - LEAST(v_total, COALESCE(v_discount_value, 0));
    ELSIF v_discount_type = 'percentage' THEN v_total := v_total - (v_total * COALESCE(v_discount_value, 0) / 100);
    END IF;
    IF v_total < 0 THEN v_total := 0; END IF;
    v_total := v_total + COALESCE(v_penalty, 0);
    RETURN v_total;
END;
$function$;

-- Trigger function to wrap calculate_expected_order_total
CREATE OR REPLACE FUNCTION public.update_order_total_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    IF TG_TABLE_NAME = 'order_items' THEN
        UPDATE orders SET total_amount = calculate_expected_order_total(COALESCE(NEW.order_id, OLD.order_id)) WHERE id = COALESCE(NEW.order_id, OLD.order_id);
    ELSE
        NEW.total_amount := calculate_expected_order_total(NEW.id);
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_update_order_total_items AFTER INSERT OR UPDATE OR DELETE ON order_items FOR EACH ROW EXECUTE FUNCTION update_order_total_trigger();
CREATE TRIGGER trg_update_order_total_details BEFORE UPDATE OF start_date, end_date, discount_type, discount_value, penalty_amount ON orders FOR EACH ROW EXECUTE FUNCTION update_order_total_trigger();


CREATE INDEX idx_orders_client_id ON public.orders (client_id);
CREATE INDEX idx_orders_date_range ON public.orders (start_date, end_date);
CREATE INDEX idx_order_items_order_id ON public.order_items (order_id);
CREATE INDEX idx_order_items_inventory_id ON public.order_items (inventory_id);
CREATE INDEX idx_clients_user_id ON public.clients (user_id);
CREATE INDEX profiles_username_idx ON public.profiles (username);
CREATE INDEX idx_coupon_redemptions_client_id ON public.discount_redemptions (client_id);
CREATE INDEX idx_coupon_redemptions_coupon_id ON public.discount_redemptions (discount_id);
CREATE INDEX idx_coupon_redemptions_order_id ON public.discount_redemptions (order_id);
